#############################################################################
# Makefile for building: AstraWin
# Generated by qmake (3.1) (Qt 6.8.0)
# Project:  AstraWin.pro
# Template: app
# Command: C:\msys64\mingw64\qt6-static\bin\qmake.exe -o Makefile AstraWin.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\msys64\mingw64\qt6-static\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\msys64\mingw64\qt6-static\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\msys64\mingw64\qt6-static\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = widl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: AstraWin.pro C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/win32-g++/qmake.conf C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/spec_pre.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/device_config.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/sanitize.conf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/gcc-base.conf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/g++-base.conf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/windows-vulkan.conf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/g++-win32.conf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/windows-desktop.conf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/qconfig.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext__clip2tri.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext__clipper.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext__poly2tri.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_glslang_glslang.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_glslang_osdependent.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_glslang_spirv.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_openwnn.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_openxr_loader.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_pinyin.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_spirv_cross.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_tcime.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3danimation.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3danimation_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dcore.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dextras.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dinput.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquick.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3drender.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_activeqt.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_activeqt_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_axserver.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_bodymovin_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_charts.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_coap.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_coap_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_core.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_core_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_datavisualization.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_datavisualization_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_dbus.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_declarativeopcua.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_designer.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_entrypoint_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_graphs.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_graphs_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_graphswidgets.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_graphswidgets_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_grpc.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_grpc_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_grpcquick.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_grpcquick_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_gui.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_help.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_help_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_httpserver.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_httpserver_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_languageserver_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_linguist.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_location.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_location_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_mqtt.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_mqtt_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_network.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_network_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_nfc.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_opcua.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_opcua_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_opengl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_openxr_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_positioning.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_protobuf.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_protobuf_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_protobufquick.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_protobufquick_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qml.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dxr.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_remoteobjects.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_repparser.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_repparser_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_scxml.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_scxmlqml.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sensors.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_serialbus.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_serialport.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sql.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_statemachine.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_statemachine_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_statemachineqml.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_svg.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_testlib.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_uitools.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_websockets.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webview.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webview_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_widgets.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_xml.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_assimp.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_assimpsceneimport.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_helpplugin.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_open62541_backend.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_openglrenderer.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qcertonlybackend.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qdirect2d.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qgif.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qicns.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qico.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qjpeg.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qminimal.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_quick3dprofiler.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmllsquickplugin.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmodernwindowsstyle.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qnetworklistmanager.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qoffscreen.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qopensslbackend.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qschannelbackend.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qscxmlecmascriptdatamodel.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qsqlite.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qsvg.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qsvgicon.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtexttospeech_mock.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtga.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtiff.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtposition_nmea.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtsysteccanbus.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtvectorcanbus.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_quicklintplugin.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qwbmp.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qwebp.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qwindows.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_rhirenderer.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_scene2d.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_windowsmediaplugin.pri \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/qt_functions.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/qt_config.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/win32-g++/qmake.conf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/spec_post.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/exclusive_builds.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/toolchain.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/default_pre.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/win32/default_pre.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/resolve_config.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/exclusive_builds_post.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/default_post.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/static_runtime.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/precompile_header.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/warn_on.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/permissions.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/qt.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/resources_functions.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/resources.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/moc.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/win32/opengl.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/uic.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/qmake_use.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/file_copies.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/win32/windows.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/testcase_targets.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/exceptions.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/yacc.prf \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/lex.prf \
		AstraWin.pro \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/styles/qmodernwindowsstyle.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/platforms/qwindows.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/iconengines/qsvgicon.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qgif.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qicns.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qico.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qjpeg.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qsvg.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qtga.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qtiff.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qwbmp.prl \
		C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qwebp.prl \
		C:/msys64/mingw64/qt6-static/lib/Qt6Widgets.prl \
		C:/msys64/mingw64/qt6-static/lib/Qt6Gui.prl \
		C:/msys64/mingw64/qt6-static/lib/Qt6Core.prl \
		C:/msys64/mingw64/qt6-static/lib/Qt6EntryPoint.prl \
		.qmake.stash \
		C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/build_pass.prf \
		images.qrc \
		style/darkstyle.qrc
	$(QMAKE) -o Makefile AstraWin.pro
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/spec_pre.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/device_config.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/sanitize.conf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/gcc-base.conf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/g++-base.conf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/windows-vulkan.conf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/g++-win32.conf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/common/windows-desktop.conf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/qconfig.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext__clip2tri.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext__clipper.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext__poly2tri.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_glslang_glslang.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_glslang_osdependent.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_glslang_spirv.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_openwnn.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_openxr_loader.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_pinyin.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_spirv_cross.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_ext_tcime.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3danimation.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3danimation_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dcore.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dextras.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dinput.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dlogic.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquick.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3drender.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_3drender_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_activeqt.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_activeqt_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_axbase_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_axcontainer.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_axserver.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_axserver_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_bluetooth.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_bodymovin_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_charts.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_charts_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_coap.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_coap_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_concurrent.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_core.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_core5compat.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_core_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_datavisualization.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_datavisualization_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_dbus.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_declarativeopcua.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_designer.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_designer_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_entrypoint_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_graphs.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_graphs_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_graphswidgets.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_graphswidgets_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_grpc.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_grpc_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_grpcquick.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_grpcquick_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_gui.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_gui_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_help.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_help_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_httpserver.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_httpserver_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsplatform.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labssettings.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_languageserver_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_linguist.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_location.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_location_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_mqtt.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_mqtt_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_multimedia.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_network.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_network_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_networkauth.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_networkauth_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_nfc.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_nfc_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_opcua.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_opcua_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_opengl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_openxr_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_positioning.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_printsupport.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_protobuf.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_protobuf_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_protobufquick.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_protobufquick_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qml.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qml_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlmeta.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmltest.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3d.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dxr.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick3dxr_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quick_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_remoteobjects.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_remoteobjects_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_repparser.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_repparser_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_scxml.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_scxml_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_scxmlqml.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_scxmlqml_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sensors.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sensors_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sensorsquick.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_serialbus.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_serialport.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_serialport_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_shadertools.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sql.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_sql_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_statemachine.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_statemachine_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_statemachineqml.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_statemachineqml_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_svg.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_svg_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_testlib.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_texttospeech.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_tools_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_uitools.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webchannel.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_websockets.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_websockets_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webview.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webview_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webviewquick.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_widgets.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_xml.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_lib_xml_private.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_assimp.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_assimpsceneimport.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_helpplugin.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_open62541_backend.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_openglrenderer.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qcertonlybackend.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qdirect2d.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qgif.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qicns.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qico.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qjpeg.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qminimal.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_local.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_native.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_quick3dprofiler.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_server.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmllsquickplugin.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qmodernwindowsstyle.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qnetworklistmanager.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qoffscreen.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qopensslbackend.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qschannelbackend.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qscxmlecmascriptdatamodel.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qsqlite.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qsvg.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qsvgicon.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtexttospeech_mock.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtga.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtiff.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtposition_nmea.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtsysteccanbus.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qttinycanbus.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtvectorcanbus.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_quicklintplugin.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qwbmp.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qwebp.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_qwindows.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_rhirenderer.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_scene2d.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/modules/qt_plugin_windowsmediaplugin.pri:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/qt_functions.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/qt_config.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/win32-g++/qmake.conf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/spec_post.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/exclusive_builds.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/toolchain.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/default_pre.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/win32/default_pre.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/resolve_config.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/exclusive_builds_post.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/default_post.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/static_runtime.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/precompile_header.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/warn_on.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/permissions.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/qt.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/resources_functions.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/resources.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/moc.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/win32/opengl.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/uic.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/qmake_use.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/file_copies.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/win32/windows.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/testcase_targets.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/exceptions.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/yacc.prf:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/lex.prf:
AstraWin.pro:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/styles/qmodernwindowsstyle.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/platforms/qwindows.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/iconengines/qsvgicon.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qgif.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qicns.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qico.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qjpeg.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qsvg.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qtga.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qtiff.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qwbmp.prl:
C:/msys64/mingw64/qt6-static/share/qt6/plugins/imageformats/qwebp.prl:
C:/msys64/mingw64/qt6-static/lib/Qt6Widgets.prl:
C:/msys64/mingw64/qt6-static/lib/Qt6Gui.prl:
C:/msys64/mingw64/qt6-static/lib/Qt6Core.prl:
C:/msys64/mingw64/qt6-static/lib/Qt6EntryPoint.prl:
.qmake.stash:
C:/msys64/mingw64/qt6-static/share/qt6/mkspecs/features/build_pass.prf:
images.qrc:
style/darkstyle.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile AstraWin.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\Users\wiean\Documents\QT\AstraWin\astrawin_plugin_import.cpp .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

.SUFFIXES:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
